services:
  faka:
    image: test/faka
    restart: always
    ports:
      - 84:80
      - 9003:9000
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
    # volumes:
    #   - dujiaoshoufaka_data:/app/.env
    networks:
      - redis_net
      - maria_db_net
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - redis_net
    expose:
      - 6379

  mariadb:
    image: mariadb:focal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=(ROOT密码)
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=oner
      - MYSQL_PASSWORD=(MYSQL_USER密码)
    networks:
      - maria_db_net
    volumes:
      - mariadb_data:/var/lib/mysql
    # ports:
    #   - 3307:3306
    # 远程管理
    expose:
      - 3306

volumes:
  mariadb_data:
  dujiaoshoufaka_data:
  redis_data:
networks:
  maria_db_net:
  redis_net:
